### ISSUE TITLE
Meteor Version

### ISSUE THREAD

**Issue by fillipefeitosa** [robertdavid010/meteor_boilerplate#1]
Hey, 

Thanks for sharing!
What version of meteor are current suporting?

**Comment by robertdavid010** [comment]
You are welcome! Currently this boilerplate is not necessarily designed to support a Meteor version. I find most projects either don't need the full boilerplate, or require a slightly different approach depending upon the application. I usually grab the pieces I need to start a project.

**Comment by robertdavid010** [comment]
Answer seems clear.
